per_run_timeout_seconds: 600
metrics_config:
  max_threads: 10
  per_query_timeout_seconds: 60
  per_column_timeout_seconds: 90
  per_run_timeout_seconds: 1800
  exclude_expensive_queries: false
  exclude_complex_queries: false
connections:
  default:
    type: snowflake
    account: "IGQTQKI-QK48619"
    user: "fred_the_sasquatch_ro"
    authenticator: SNOWFLAKE_JWT
    private_key_file: "conf/rsa_key_snowflake.p8"
    private_key_file_pwd: "yetisson"
    databases:
      "TEMPLATE_DATA":
        database: "TEMPLATE_DATA"
