max_threads: 10

run_timeout_seconds: 1200
connection_timeout_seconds: 600
query_timeout_seconds: 60

exclude_expensive_queries: true
exclude_complex_queries: true

connections:
  default:
    type: snowflake
    params:
      account: "IGQTQKI-QK48619"
      user: "fred_the_sasquatch_ro"
      private_key_file: "conf/rsa_key_snowflake.p8"
      private_key_file_pwd: "yetisson"
    include:
      - snowflake_sample_data.tpch_sf100
