
per_run_timeout_seconds: 600

metrics_config:
  # Default timeouts and metric collection configs. Can be overridden per connection.
  max_threads: 10
  per_query_timeout_seconds: 60
  per_column_timeout_seconds: 60
  per_database_timeout_seconds: 120
  exclude_expensive_queries: false

connections:
  sample:
    type: snowflake
    # If the type is snowflake, this matches snowflake's connection.toml entries
    account: IGQTQKI-QK48619
    user: fred_the_sasquatch_ro
    # $ENVVAR is the syntax to get from environment variable
    # password: $SASQUATCH_PASSWORD
    private_key_file: conf/rsa_key_snowflake.p8
    private_key_file_pwd: $SNOWFLAKE_PRIVATE_KEY_PASSWORD
    warehouse: COMPUTE_WH
    databases:
#      climate_bi:
#        database: GLOBAL_WEATHER__CLIMATE_DATA_FOR_BI
      snowflake_sample_data:
        database: SNOWFLAKE_SAMPLE_DATA
        include_schemas:
          - TPCH_SF100
        metrics_config: # override metrics
          max_threads: 10
          per_query_timeout_seconds: 300
          exclude_expensive_queries: false
          exclude_complex_queries: false
          per_database_timeout_seconds: 600
